// Autogenerated wrapper to mount the provided wireframe component without changes.
// Do not edit the original file under src/wf1/.
// This file simply re-exports the default export for routing at /scene0.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import Comp from '../wf1/ready_72_scene_0_intro_pixel_rebuild.jsx';
export default Comp;
